
public enum MessageType {
	LOGIN, LOGINNOTFOUND, INCORRECTLOGIN, SHOWUSERSTATS, CREATEACCT, LOGINSUCCESS, CHOOSEGAMETYPE, 
	STARTGAME, JOINGAME, DUPLICATENAME, INCORRECTNAME, REQUESTUSERCOUNT, RESPONSEUSERCOUNT, GAMEBEGIN, WAITUNTILMAX,
	USERCTCHANGED, USERENTERED, ROOMFULL, FINDSECRETWRD, ROOMFILLED, CURRSECRETWORD, PLAY, WAITFORPLAY, GUESSEDLETTER, GUESSEDWORD,
	GUESSEDCORRECTLYLETTER, NOTIFYCORRECTNESSLETTER, GUESSEDINCORRECTLYLETTER, NOTIFYINCORRECTNESSLETTER, GUESSEDCORRECTLYWORD,
	NOTIFYCORRECTNESSWORD, GUESSEDINCORRECTLYWORD, NOTIFYINCORRECTNESSWORD, IWIN, ILOST,NEXTPERSON, ALLLOSE, HEDEAD, THANKYOU
}
